name: Site Health Check

on:
  schedule:
    - cron: '0 */6 * * *'  # Roda a cada 6 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  health_check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check site availability
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://opimpact.github.io/oportunidades-de-impacto/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
          retry-all: true

      - name: Performance Check
        id: perf_check
        uses: actions/github-script@v6
        with:
          script: |
            const start = Date.now();
            const response = await fetch('https://opimpact.github.io/oportunidades-de-impacto/');
            const timeMs = Date.now() - start;
            
            if (timeMs > 3000) {
              throw new Error(`Site response time (${timeMs}ms) is too high`);
            }
            console.log(`Site response time: ${timeMs}ms`);

      - name: Send notification if check fails
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Site Health Check Failed',
              body: `Health check failed at ${new Date().toISOString()}
              
              Please verify:
              1. Site availability
              2. Performance issues
              
              Site URL: https://opimpact.github.io/oportunidades-de-impacto/`
            });
